spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:h2:mem:lissenlydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Cho phép cross-origin từ Angular
management.endpoints.web.exposure.include=*

# YouTube API Key (Hãy dán Key của bạn vào đây)
youtube.api.key=AIzaSyBedxPCmoUaiSO-nrYHVIgZzDKMHgoQDpQ
